### ISSUE TITLE
Prepare final milestone assignments

### ISSUE THREAD

**Issue by danielley** [vip-aerospace/keao#50]
- [ ] Final Poster 11/23

- [ ] Final demonstration 11/30

- [ ] Final presentation 12/07

- [ ] Final report 12/14

Others:

- [ ] Tutorials per subsystem check

- [ ] Availability requests to schedule presentation times

- [ ] Practice/review times with team and mentors

**Comment by danielley** [comment]
Files will be put in Google Drive folder here: https://drive.google.com/drive/folders/1GWzqM4a4bqOmMa4D4V3ePB0HUyfoyTCK?usp=sharing

**Comment by danielley** [comment]
Final poster
https://drive.google.com/file/d/1W4wZW9YXBRZGXgPcCn3PQG2_YO0sqFgp/view?usp=sharing
